%% Inputs
%#ok<*UNRCH>
mode = 'oneshot';

if isequal(mode,'oneshot')
  clear
  clc
  
  n_frames = 1;
  cc =  3.00;
  xx =  0.25;
  yy =  0.0;
  zz =  0.020;
  z_guar = 0.025;
elseif isequal(mode,'sweep')
  clear
  clc
  
  n_frames = 250;
  cc = 2.25*cosd(6.0*linspace(0,360,n_frames)-90)+4.5;
  xx = 0.4*sind(1.0*linspace(0,360,n_frames));
  yy = 0.1*cosd(1.0*linspace(0,360,n_frames));
  zz = 0.05*sind(3.0*linspace(0,360,n_frames)-90);
  z_guar = 0.01;
elseif isequal(mode,'sim')
  n_frames = length(w_r(1,:));
  cc = w_r(1,:);
  xx = w_r(2,:);
  yy = w_r(3,:);
  zz = w_r(4,:);
end

fs = 15;
delay_ms = 0;
record = false;
video_filename = 'mp_qallocator_anim_6dof_sim_replay_ex4.mp4';
%% Setup
A(1) = mp_model_actuator('thrust','2nd');
A(2) = mp_model_actuator('thrust','2nd');
A(3) = mp_model_actuator('thrust','2nd');
A(4) = mp_model_actuator('thrust','2nd');
G(1) = mp_model_vehicle('z-accl');
G(2) = mp_model_vehicle('x-rate');
G(3) = mp_model_vehicle('y-rate');
G(4) = mp_model_vehicle('z-rate');
H(1) = mp_model_mpu6000('accl',3);
H(2) = mp_model_mpu6000('gyro',3);
H(3) = mp_model_mpu6000('gyro',3);
H(4) = mp_model_mpu6000('gyro',3);
plant = mp_quad_6dof_t(A,H,@d,@n, ...
                       [0 0 0]', ...
                       [0 0 0]', ...
                       [1 0 0 0]', ...
                       [0 0 0]', ...
                       [0 0 0 0]');

tol = 1e-6;
l_x = plant.l_x;
l_y = plant.l_y;
k_f2t = plant.k_f2t;
f_min = plant.f_min;
f_max = plant.f_max;
z_max = 2*k_f2t*f_max;
if (rank(plant.H_f2w) > 3)
  z_guar = mp_saturation(0,z_guar,z_max);
else
  z_guar = 0;
end

figure(1),clf(1)

subplot(1,2,1),hold on,grid on

v_f = [0 0 0 0
       0 0 0 1
       0 0 1 0
       0 0 1 1
       0 1 0 0
       0 1 0 1
       0 1 1 0
       0 1 1 1
       1 0 0 0
       1 0 0 1
       1 0 1 0
       1 0 1 1
       1 1 0 0
       1 1 0 1
       1 1 1 0
       1 1 1 1]'*(f_max-f_min)+f_min;
v_w = plant.H_f2w*v_f;

K_xy = convhull(v_w(2,:),v_w(3,:));
plot(v_w(2,K_xy),v_w(3,K_xy), ...
     'color','k', ...
     'linewidth',1, ...
     'marker','none', ...
     'markersize',20)
plot([0 v_w(2,2)],[0 v_w(3,2)], ...
     'color',0.7*[1 1 1], ...
     'linewidth',1, ...
     'linestyle','-', ...
     'marker','none')
plot([0 v_w(2,3)],[0 v_w(3,3)], ...
     'color',0.7*[1 1 1], ...
     'linewidth',1, ...
     'linestyle','-', ...
     'marker','none')
plot([0 v_w(2,5)],[0 v_w(3,5)], ...
     'color',0.7*[1 1 1], ...
     'linewidth',1, ...
     'linestyle','-', ...
     'marker','none')
plot([0 v_w(2,9)],[0 v_w(3,9)], ...
     'color',0.7*[1 1 1], ...
     'linewidth',1, ...
     'linestyle','-', ...
     'marker','none')

s1_1 = surf(zeros(2,9),zeros(2,9),zeros(2,9), ...
            'facecolor',[0 0.7 0], ...
            'facealpha',0.25, ...
            'linestyle','none');
h1_1 = plot(zeros(1,11),zeros(1,11), ...
            'color',[0 0.7 0], ...
            'linewidth',6, ...
            'linestyle','-', ...
            'marker','none');
h1_2 = plot([0 0 0],[0 0 0], ...
            'color','k', ...
            'linewidth',1, ...
            'linestyle','-.');
h1_3 = plot(0,0, ...
            'color','b', ...
            'marker','.', ...
            'markersize',20);
h1_4 = plot(0,0, ...
            'color','b', ...
            'marker','o', ...
            'markersize',17.5, ...
            'linewidth',2);
h1_5 = plot(0,0, ...
            'color','r', ...
            'marker','.', ...
            'markersize',40);
h1_6 = plot(0,0, ...
            'color',0.3*[1 1 1], ...
            'linewidth',3, ...
            'marker','s', ...
            'markersize',35);

x_legend = [-0.05 -0.05  -0.50 -0.50 -0.50 -0.05];
y_legend = [ 0.82 0.68  0.82  0.75  0.68 0.75]+0.015-0.035;

dx_legend = 0.032;
dy_legend = 0.022;
DX1_legend = 0.07;
DX2_legend = 0.62;
DY_legend = 0.05;
dx_legend_text = 0.07;
dy_legend_text = 0;

surf([min(x_legend)-DX1_legend min(x_legend)-DX1_legend
      max(x_legend)+DX2_legend max(x_legend)+DX2_legend], ...
     [min(y_legend)-DY_legend max(y_legend)+DY_legend
      min(y_legend)-DY_legend max(y_legend)+DY_legend], ...
     [0 0; 0 0],'linestyle','-','edgecolor','k','facecolor','w')
surf(x_legend(1)+dx_legend*[-1  1; -1  1], ...
     y_legend(1)+dy_legend*[ 1  1; -1 -1], ...
      [0 0; 0 0], ...
  'facecolor',[0 0.7 0], ...
  'facealpha',0.25, ...
  'linestyle','none')
plot(x_legend(1)+dx_legend*[-1 1 1 -1 -1 1], ...
     y_legend(1)+dy_legend*[1 1 -1 -1 1 1], ...
  'color',[0 0.7 0], ...
  'linewidth',6, ...
  'linestyle','-')
plot(x_legend(2)+dx_legend*[-1 1], ...
     y_legend(2)*[1 1], ...
  'color','k', ...
  'linewidth',1)
plot(x_legend(3),y_legend(3), ...
  'color','b', ...
  'marker','.', ...
  'markersize',20);
plot(x_legend(3),y_legend(3), ...
  'color','b', ...
  'marker','o', ...
  'markersize',17.5, ...
  'linewidth',2, ...
  'linestyle','none');
plot(x_legend(4),y_legend(4), ...
  'color','r', ...
  'marker','.', ...
  'markersize',40, ...
  'linestyle','none');
plot(x_legend(5),y_legend(5), ...
  'color',0.3*[1 1 1], ...
  'linewidth',3, ...
  'marker','s', ...
  'markersize',35, ...
  'linestyle','none')
plot(x_legend(6)+dx_legend*[-1 1],y_legend(6)*[1 1], ...
  'color','k', ...
  'linewidth',1, ...
  'linestyle','-.')

text(x_legend(1)+dx_legend_text, ...
     y_legend(1)+dy_legend_text, ...
  'Feas. Wrenches w/ Guar. Z','fontsize',fs)
text(x_legend(2)+dx_legend_text, ...
     y_legend(2)+dy_legend_text, ...
  'Proj. of All Feas. Wrenches','fontsize',fs)
text(x_legend(3)+dx_legend_text, ...
     y_legend(3)+dy_legend_text, ...
  'Req. Wrench','fontsize',fs)
text(x_legend(4)+dx_legend_text, ...
     y_legend(4)+dy_legend_text, ...
  'Alloc. Wrench','fontsize',fs)
text(x_legend(5)+dx_legend_text, ...
     y_legend(5)+dy_legend_text, ...
  'Realized Wrench','fontsize',fs)
text(x_legend(6)+dx_legend_text, ...
     y_legend(6)+dy_legend_text, ...
  'XY-Torque Dir.','fontsize',fs)

axis equal
xlabel('X-Torque [N-m]','fontsize',fs)
ylabel('Y-Torque [N-m]','fontsize',fs)
set(gca,'fontsize',fs)
set(gca,'xtick',-10:0.2:10,'ytick',-0.7:0.2:0.9)
set(gca,'xlim',0.6*[-1 1],'ylim',[-0.7 0.9])

subplot(1,2,2),hold on,grid on

K_cz = convhull(v_w(4,:),v_w(1,:));
plot(v_w(4,K_cz),v_w(1,K_cz), ...
     'color','k', ...
     'linewidth',1, ...
     'marker','none', ...
     'markersize',20)

if (z_guar > 0)
  s2_1_vis = 'on';
else
  s2_1_vis = 'off';
end
s2_1 = surf(min(z_guar,z_max)*[-1 1; -1 1], ...
            20*[-1 -1; 1 1], ...
            0*ones(2,2), ...
            'facecolor',0.7*[1 1 1], ...
            'facealpha',0.1, ...
            'linestyle','-', ...
            'visible',s2_1_vis);
s2_2 = surf(zeros(2,5), ...
            zeros(2,5), ...
            zeros(2,5), ...
            'facecolor',[0 0.7 0], ...
            'facealpha',0.25, ...
            'linestyle','none');

h2_1 = plot(zeros(1,6), ...
            zeros(1,6), ...
            'color',[0 0.7 0], ...
            'linewidth',6);
h2_2 = plot(0, ...
            2*(f_max+f_min), ...
            'color','b', ...
            'marker','.', ...
            'markersize',20);
h2_3 = plot([0 0],[0 0], ...
            'color','k', ...
            'linewidth',1, ...
            'linestyle','-.', ...
            'marker','none');
h2_4 = plot(0, ...
            2*(f_max+f_min), ...
            'color','b', ...
            'marker','o', ...
            'markersize',17.5, ...
            'linewidth',2);
h2_5 = plot(0, ...
            2*(f_max+f_min), ...
            'color','r', ...
            'marker','.', ...
            'markersize',40);
h2_6 = plot(0, ...
            2*(f_max+f_min), ...
            'color',0.3*[1 1 1], ...
            'linewidth',3, ...
            'marker','s', ...
            'markersize',35);

x_legend = [-0.025 -0.025  -0.30 -0.30 -0.30 -0.025]/4*3/4;
y_legend = [1 -1 1 0 -1 0]*0.625+10.5;

dx_legend = 0.018/4*3/4;
dy_legend = 0.20;
DX1_legend = 0.05/4*3/4;
DX2_legend = 0.375/4*3/4;
DY_legend = 0.45;
dx_legend_text = 0.04/4*3/4;
dy_legend_text = 0;

surf([min(x_legend)-DX1_legend min(x_legend)-DX1_legend
      max(x_legend)+DX2_legend max(x_legend)+DX2_legend], ...
     [min(y_legend)-DY_legend max(y_legend)+DY_legend
      min(y_legend)-DY_legend max(y_legend)+DY_legend], ...
     [0 0; 0 0],'linestyle','-','edgecolor','k','facecolor','w')
surf(x_legend(1)+dx_legend*[-1  1; -1  1], ...
     y_legend(1)+dy_legend*[ 1  1; -1 -1], ...
      [0 0; 0 0], ...
  'facecolor',[0 0.7 0], ...
  'facealpha',0.25, ...
  'linestyle','none')
plot(x_legend(1)+dx_legend*[-1 1 1 -1 -1 1], ...
     y_legend(1)+dy_legend*[1 1 -1 -1 1 1], ...
  'color',[0 0.7 0], ...
  'linewidth',6, ...
  'linestyle','-')
plot(x_legend(2)+dx_legend*[-1 1], ...
     y_legend(2)*[1 1], ...
  'color','k', ...
  'linewidth',1)
plot(x_legend(3),y_legend(3), ...
  'color','b', ...
  'marker','.', ...
  'markersize',20);
plot(x_legend(3),y_legend(3), ...
  'color','b', ...
  'marker','o', ...
  'markersize',17.5, ...
  'linewidth',2, ...
  'linestyle','none');
plot(x_legend(4),y_legend(4), ...
  'color','r', ...
  'marker','.', ...
  'markersize',40, ...
  'linestyle','none');
plot(x_legend(5),y_legend(5), ...
  'color',0.3*[1 1 1], ...
  'linewidth',3, ...
  'marker','s', ...
  'markersize',35, ...
  'linestyle','none')
surf(x_legend(6)+dx_legend*[-1  1; -1  1], ...
     y_legend(6)+dy_legend*[ 1  1; -1 -1], ...
      [0 0; 0 0], ...
  'facecolor',0.7*[1 1 1], ...
  'facealpha',0.1, ...
  'linestyle','none')
plot(x_legend(6)+dx_legend*[-1 1 1 -1 -1 1], ...
     y_legend(6)+dy_legend*[1 1 -1 -1 1 1], ...
  'color','k', ...
  'linewidth',1, ...
  'linestyle','-')

text(x_legend(1)+dx_legend_text, ...
     y_legend(1)+dy_legend_text, ...
  'Feas. Wrenches w/ XY','fontsize',fs)
text(x_legend(2)+dx_legend_text, ...
     y_legend(2)+dy_legend_text, ...
  'Proj. of All Feas. Wrenches','fontsize',fs)
text(x_legend(3)+dx_legend_text, ...
     y_legend(3)+dy_legend_text, ...
  'Req. Wrench','fontsize',fs)
text(x_legend(4)+dx_legend_text, ...
     y_legend(4)+dy_legend_text, ...
  'Alloc. Wrench','fontsize',fs)
text(x_legend(5)+dx_legend_text, ...
     y_legend(5)+dy_legend_text, ...
  'Realized Wrench','fontsize',fs)
text(x_legend(6)+dx_legend_text, ...
     y_legend(6)+dy_legend_text, ...
  'Guaranteed Z-Torque','fontsize',fs)

xlabel('Z-Torque [N-m]','fontsize',fs)
ylabel('Collective Thrust [N]','fontsize',fs)
set(gca,'fontsize',fs)
set(gca,'xlim',0.075*[-1 1],'ylim',[-2 12.0])
set(gca,'xtick',-10:0.025:10,'ytick',-20:2:20)
%% Start Video
if (record)
  vid = VideoWriter(video_filename,'MPEG-4');
  vid.Quality = 100;
  vid.FrameRate = 15;
  open(vid);
  for k=1:1
    frame = getframe(gcf);
    writeVideo(vid,frame);
  end
end
%% Run Loop
for ii=1:length(cc)
  %% Run Algorithm
  w_req = [cc(ii) xx(ii) yy(ii) zz(ii)]';
  [w_alloc,f_alloc] = ...
    mp_qallocator(w_req,z_guar,plant.H_f2w,l_x,l_y,k_f2t,f_min,f_max,tol);
  %% Pre-Plotting
  c_req = w_req(1);
  x_req = w_req(2);
  y_req = w_req(3);
  z_req = w_req(4);
  
  c_alloc = w_alloc(1);
  x_alloc = w_alloc(2);
  y_alloc = w_alloc(3);
  z_alloc = w_alloc(4);
  
  z_thresh = min(abs(z_req),z_guar);
  v_a = [2*l_y*(f_max-f_min) 0 0]';
  v_b = [l_y*(f_max-f_min) l_x*(f_max-f_min) k_f2t*(f_max-f_min)]';
  v_c = [0 2*l_x*(f_max-f_min) 0]';
  v_d = [0 0 z_max]';
  v_xy = zeros(2,8);
  if (z_thresh < v_b(3))
    k_ab = (z_thresh-v_a(3))/(v_b(3)-v_a(3));
    k_cb = (z_thresh-v_c(3))/(v_b(3)-v_c(3));
    v_xy(1,1) = (1-k_ab)*v_a(1)+k_ab*v_b(1);
    v_xy(2,1) = (1-k_ab)*v_a(2)+k_ab*v_b(2);
    v_xy(1,2) = (1-k_cb)*v_c(1)+k_cb*v_b(1);
    v_xy(2,2) = (1-k_cb)*v_c(2)+k_cb*v_b(2);
    v_xy(1,3) = -v_xy(1,2);
    v_xy(2,3) =  v_xy(2,2);
    v_xy(1,4) = -v_xy(1,1);
    v_xy(2,4) =  v_xy(2,1);
    v_xy(1,5) = -v_xy(1,1);
    v_xy(2,5) = -v_xy(2,1);
    v_xy(1,6) = -v_xy(1,2);
    v_xy(2,6) = -v_xy(2,2);
    v_xy(1,7) =  v_xy(1,2);
    v_xy(2,7) = -v_xy(2,2);
    v_xy(1,8) =  v_xy(1,1);
    v_xy(2,8) = -v_xy(2,1);
  else
    k_bd = (z_thresh-v_b(3))/(v_d(3)-v_b(3));
    v_xy(1,1) = (1-k_bd)*v_b(1)+k_bd*v_d(1);
    v_xy(2,1) = (1-k_bd)*v_b(2)+k_bd*v_d(2);
    v_xy(1,2) =  v_xy(1,1);
    v_xy(2,2) =  v_xy(2,1);
    v_xy(1,3) = -v_xy(1,1);
    v_xy(2,3) =  v_xy(2,1);
    v_xy(1,4) = -v_xy(1,1);
    v_xy(2,4) =  v_xy(2,1);
    v_xy(1,5) = -v_xy(1,1);
    v_xy(2,5) = -v_xy(2,1);
    v_xy(1,6) = -v_xy(1,1);
    v_xy(2,6) = -v_xy(2,1);
    v_xy(1,7) =  v_xy(1,1);
    v_xy(2,7) = -v_xy(2,1);
    v_xy(1,8) =  v_xy(1,1);
    v_xy(2,8) = -v_xy(2,1);
  end

  H_xy = plant.H_f2w(2:3,:);
  w_xy = [x_alloc y_alloc]';
  f_xy = H_xy'/(H_xy*H_xy')*w_xy;
  
  if (rank(plant.H_f2w) == 3)
    c_bot = 4*max(f_min-f_xy);
    c_top = 4*min(f_max-f_xy);
    
    H_cxy = plant.H_f2w(1:3,:);
    w_bot = [c_bot x_alloc y_alloc]';
    w_top = [c_top x_alloc y_alloc]';
    z_bot = plant.H_f2w(4,:)*H_cxy'/(H_cxy*H_cxy')*w_bot;
    z_top = plant.H_f2w(4,:)*H_cxy'/(H_cxy*H_cxy')*w_top;
    
    v_cz = zeros(2,4);
    v_cz(:,1) = [c_bot z_bot]';
    v_cz(:,2) = [c_bot z_bot]';
    v_cz(:,3) = [c_top z_top]';
    v_cz(:,4) = [c_top z_top]';
  elseif (rank(plant.H_f2w) == 4)
    b1 = 4*k_f2t*max(f_min-f_xy(sign(plant.H_f2w(4,:)) > 0));
    b2 = 4*k_f2t*max(f_min-f_xy(sign(plant.H_f2w(4,:)) < 0));
    b3 = 4*k_f2t*min(f_max-f_xy(sign(plant.H_f2w(4,:)) > 0));
    b4 = 4*k_f2t*min(f_max-f_xy(sign(plant.H_f2w(4,:)) < 0));
    A = [ k_f2t  k_f2t -k_f2t -k_f2t; 1 -1 -1  1]';
    b = [b1 b2 -b3 -b4]';
    
    v_cz = zeros(2,4);
    v_cz(:,1) = A([1 4],:)\b([1 4]);
    v_cz(:,2) = A([1 2],:)\b([1 2]);
    v_cz(:,3) = A([3 2],:)\b([3 2]);
    v_cz(:,4) = A([3 4],:)\b([3 4]);
  end
  %% Draw Figures
  set(s1_1,'xdata',[v_xy(1,[1:8 1]); zeros(1,9)], ...
           'ydata',[v_xy(2,[1:8 1]); zeros(1,9)], ...
           'zdata',0*ones(2,9));
  set(h1_1,'xdata',v_xy(1,[1:8 1 2 3]), ...
           'ydata',v_xy(2,[1:8 1 2 3]));
  set(h1_2,'xdata',[0 x_alloc x_req], ...
           'ydata',[0 y_alloc y_req]);
  set(h1_3,'xdata',x_req, ...
           'ydata',y_req);
  set(h1_4,'xdata',x_req, ...
           'ydata',y_req);
  set(h1_5,'xdata',x_alloc, ...
           'ydata',y_alloc);
  set(h1_6,'xdata',plant.H_f2w(2,:)*f_alloc, ...
           'ydata',plant.H_f2w(3,:)*f_alloc);
  
  set(s2_2,'xdata',[v_cz(2,[2 1]); v_cz(2,[3 4])], ...
           'ydata',[v_cz(1,[2 1]); v_cz(1,[3 4])], ...
           'zdata',0*ones(2,2));
  set(h2_1,'xdata',v_cz(2,[1:4 1 2 3]), ...
           'ydata',v_cz(1,[1:4 1 2 3]));
  set(h2_2,'xdata',z_req, ...
           'ydata',c_req);
  set(h2_3,'xdata',[z_req z_alloc], ...
           'ydata',[c_req c_alloc]);
  set(h2_4,'xdata',z_req, ...
           'ydata',c_req);
  set(h2_5,'xdata',z_alloc, ...
           'ydata',c_alloc);
  set(h2_6,'xdata',plant.H_f2w(4,:)*f_alloc, ...
           'ydata',plant.H_f2w(1,:)*f_alloc);
  
  if (delay_ms > 0)
    mp_pause(delay_ms)
  end
  drawnow
  %% Record Video
  if (record)
    frame = getframe(gcf);
    writeVideo(vid,frame);
  end
end
%% End Video
if (record)
  for k=1:1
    frame = getframe(gcf);
    writeVideo(vid,frame);
  end
  close(vid);
end
